#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ts="$(date +%Y-%m-%d)"
dest="${1:-"$HOME/Desktop/pmmm-bot-canary_review_bundle_${ts}"}"

files=(
  TODO.md
  src/config.rs
  src/main.rs
  src/clients/clob_rest.rs
  src/clients/clob_ws_user.rs
  src/execution/completion.rs
  src/execution/order_manager.rs
  src/state/inventory.rs
  src/state/state_manager.rs
  src/strategy/engine.rs
  src/strategy/quote_engine.rs
  src/strategy/risk.rs
)

cd "$root_dir"

rm -rf "$dest"
mkdir -p "$dest"

rsync -aR "${files[@]}" "$dest/"

cat > "$dest/README_REVIEW_BUNDLE.md" <<'EOF'
# pmmm-bot-canary review bundle

This folder contains only the source files relevant to the “one-sided fills / strict pairing / 20c floor / completion” changes.

It is generated by `ops/review/make_one_sided_fills_bundle.sh`.

## How to use
- Share this folder with a reviewer.
- Ask them to review only the files inside it (paths preserved under `src/`).
EOF

echo "Wrote review bundle to: $dest"
